version: "3.7"

services:
  semcomp25:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - semcomp25-redis
    volumes:
      - ./logs:/app/logs

  semcomp25-redis:
    image: redis:7.0.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
